export type BatchLevel =
  | "BEGINNER"
  | "CORE_1"
  | "CORE_2"
  | "CORE_3"
  | "CORE_4"
  | "BRIDGE"
  | "INTERMEDIATE_1"
  | "INTERMEDIATE_2"
  | "INTERMEDIATE_3"
  | "ADVANCE_1"
  | "ADVANCE_2"
  | "ELITE";

export type SyllabusLevel = {
  level: BatchLevel;
  label: string;
  codePrefix: string;
  lectures: number;
  durationMonths: number;
  topics: string[];
};

export const SYLLABUS: SyllabusLevel[] = [
  {
    level: "BEGINNER",
    label: "Beginner Level",
    codePrefix: "BG",
    lectures: 24,
    durationMonths: 3,
    topics: [
      "Lecture 1: Introduction → Ranks, Files, Diagonals, Board setup, Rook, Square names",
      "Lecture 2: Bishop, King, Queen",
      "Lecture 3: Knight, Pawn, Notation",
      "Lecture 4: Piece value (Quantitative & Qualitative) & Profitable captures",
      "Lecture 5: Captures, Mix practice (Hanging pieces)",
      "Lecture 6: Check, Out of check, Checkmate introduction",
      "Lecture 7: Mate in 1 practice position",
      "Lecture 8: Castling & its legality, En passant",
      "Lecture 9: 3 Ways to protect Hanging Pieces, Chess.com,lichess ID creation & intro",
      "Lecture 10: Student game analysis",
      "Lecture 11: Check in 2 moves, Pawn promotion",
      "Lecture 12: Test-1",
      "Lecture 13: Rules of Draw→ 50-move rule, insufficient material,3-fold repetition",
      "Lecture 14: One-Queen checkmate (L & cutoff rules) + two Rook Checkmate(ladder)",
      "Lecture 15: Draw by Stealmate Practice",
      "Lecture 16: Mate in 1 practice + Easy Mate in 2",
      "Lecture 17: Scholers Mate & Fools Mate",
      "Lecture 18: The Fork",
      "Lecture 19: One Rook CheckMate",
      "Lecture 20: Double Attack",
      "Lecture 21: Opening principles: 5 rules",
      "Lecture 22: Punish the Scholors Mate",
      "Lecture 23: Student Game Analysis",
      "Lecture 24: Test-2",
    ],
  },
  {
    level: "CORE_1",
    label: "Core Level 1",
    codePrefix: "CL1",
    lectures: 24,
    durationMonths: 4,
    topics: [
      "Lecture 1: Revision Of Begginer Level",
      "Lecture 2: The Pin",
      "Lecture 3: The Skewer",
      "Lecture 4: Eliminate the Defence",
      "Lecture 5: Student Game Analysis",
      "Lecture 6: Hard Mate in 2, intro & practice",
      "Lecture 7: The BatterY",
      "Lecture 8: Openning Traps ( Domino’s Mate, Legals Mate, Fischer pole Trap, Budapest trap)",
      "Lecture 9: Practice: Discovered attack",
      "Lecture 10: Italian opening → Basics",
      "Lecture 11: Decoy & Deflection",
      "Lecture 12: Test-1",
      "Lecture 13: Passed Pawn, Magic Square",
      "Lecture 14: Opposition → Frontal, Side & Diagonal",
      "Lecture 15: Caro-Kann Exchange + Advance Basics, Theory intro",
      "Lecture 16: checkmate Pattern ( Back Rank mate, Lollis Mate, Dovetailas mate)",
      "Lecture 17: checkmate Pattern R+N ( Anasthisia mate, Hooks Mate, Arabian mate)",
      "Lecture 18: Checkmate with two Bishops + Revision 1 Rook Checkmate",
      "Lecture 19: Overloading",
      "Lecture 20: Trapping Opponents Pieces",
      "Lecture 21: Colliner Move ( Easy) + Student Game Analysis",
      "Lecture 22: Introduction of London System",
      "Lecture 23: Checkmate Threat",
      "Lecture 24: Test 2",
    ],
  },
  {
    level: "CORE_2",
    label: "Core Level 2",
    codePrefix: "CL2",
    lectures: 24,
    durationMonths: 3,
    topics: [
      "Lecture 1: Revision Of core Level-1",
      "Lecture 2: X- Ray Attack",
      "Lecture 3: Zwischenzug (Intermediate move)",
      "Lecture 4: Desperado (A piece is lost but can still help)",
      "Lecture 5: Mate in 3 practice",
      "Lecture 6: Open Files and Outposts",
      "Lecture 7: Student games analysis",
      "Lecture 8: Attraction",
      "Lecture 9: Clearence",
      "Lecture 10: London System (traps)",
      "Lecture 11: London System (Master Games)",
      "Lecture 12: Test-1",
      "Lecture 13: Pawn Breakthrough",
      "Lecture 14: Triangulation",
      "Lecture 15: Caro-Kann classical Variation(Tartakower & Main line Bf5)",
      "Lecture 16: checkmate Pattern ( Smothered mate,boden’s mate, Balestra mate)",
      "Lecture 17: Introduction of Kings Indian Defence",
      "Lecture 18: Opening Traps: (shilling Kostic gambit, England gambit, (pros and cons.)",
      "Lecture 19: Windmill attack",
      "Lecture 20: Student Game Analysis",
      "Lecture 21: Colliner Move ( Medium)",
      "Lecture 22: Openings Traps in carokann",
      "Lecture 23: Basic Rook endgings( Lucena & Phillodor)",
      "Lecture 24: Test 2",
    ],
  },
  {
    level: "CORE_3",
    label: "Core Level 3",
    codePrefix: "CL3",
    lectures: 24,
    durationMonths: 3,
    topics: [
      "Lecture 1: Revision Of core Level-2",
      "Lecture 2: CCTP Rule calculation",
      "Lecture 3: Candidate Moves",
      "Lecture 4: Principle of two Weekness",
      "Lecture 5: Mate in 3 practice",
      "Lecture 6: Zugzwang Practice",
      "Lecture 7: Student games analysis",
      "Lecture 8: Defensive Moves",
      "Lecture 9: Quite Moves",
      "Lecture 10: London System Revision + Master Game",
      "Lecture 11: Sholdering",
      "Lecture 12: Test-1",
      "Lecture 13: Introduction Sicillian Defence",
      "Lecture 14: Good pin vs Bad Pin ( Kasparov System)",
      "Lecture 15: Caro-Kann Advance Variation ideas( backward pawn target)",
      "Lecture 16: Intermezzo",
      "Lecture 17: Kings Indian Defence- Ideas",
      "Lecture 18: Stonewall Opening Attack",
      "Lecture 19: Rook endgame( Vancura Position and Savedra position, revision lucena , phillodor)",
      "Lecture 20: Student Game Analysis",
      "Lecture 21: Good bishop vs Bad Bishops",
      "Lecture 22: Attack on Castled King – Part 1",
      "Lecture 23: Basic Bishop Endings",
      "Lecture 24: Test 2",
    ],
  },
  {
    level: "CORE_4",
    label: "Core Level 4",
    codePrefix: "CL4",
    lectures: 32,
    durationMonths: 4,
    topics: [
      "Lecture 1: Revision of core 3",
      "Lecture 2: Candidate Moves-part 2",
      "Lecture 3: Same color Bishop Endgame",
      "Lecture 4: Bishop vs Knight Endgame",
      "Lecture 5: Outpost Square Strategy",
      "Lecture 6: Distant Opposition",
      "Lecture 7: Student games analysis",
      "Lecture 8: Colliner Moves(Hard Part 1)",
      "Lecture 9: Opposite color bishop Endgame",
      "Lecture 10: Fortress- Part 1",
      "Lecture 11: Queen vs 7th Rank Pawn",
      "Lecture 12: Test-1",
      "Lecture 13: Sicillian Defence- Taimanov Variation",
      "Lecture 14: Contering sicillian with Delayed Alpin Variation",
      "Lecture 15: Tactical theme- Clearence",
      "Lecture 16: Student Game Analysis",
      "Lecture 17: Minority Attack",
      "Lecture 18: Defensive Moves- part 2",
      "Lecture 19: Rook endgame( Pawn on 7th Rank)",
      "Lecture 20: Student Game Analysis",
      "Lecture 21: Bishop vs Knight",
      "Lecture 22: London System Full Revison",
      "Lecture 23: Weak Squares",
      "Lecture 24: Good Bishop vs Bad Knight",
      "Lecture 25: Good Knight vs Bad Bishop",
      "Lecture 26: Converting Rook Endgames",
      "Lecture 27: Greek Gift Sacrifice",
      "Lecture 28: Student Game Analysis",
      "Lecture 29: Theoretical Bishop Endings",
      "Lecture 30: Basic Knight Endgame",
      "Lecture 31: Legendary King Walk",
      "Lecture 32: Test 2",
    ],
  },
  {
    level: "BRIDGE",
    label: "Bridge Level",
    codePrefix: "BR",
    lectures: 8,
    durationMonths: 1,
    topics: [
      "Lecture 1: Pin, Skewer,Deflection, Attraction,Overloading,X-ray attack,Intermezzo",
      "Lecture 2: Positional revision (outpost, week square, minority attack, good B vs Bad B, Good K vs Bad Bishop)",
      "Lecture 3: Endgame( Full Rook endinsg)",
      "Lecture 4: endgame( same color and opposite color Bishops)",
      "Lecture 5: Attack & Defence(Greek gift, defensive move,counter attack)",
      "Lecture 6: Distant Opposition,pawn break through, triangulation.",
      "Lecture 7: Opening Revision( Caro Kann & sicilian Taimanov)",
      "Lecture 8: Opening Revision( London system)",
    ],
  },
  {
    level: "INTERMEDIATE_1",
    label: "Intermediate Level 1",
    codePrefix: "IM1",
    lectures: 36,
    durationMonths: 4,
    topics: [
      "Lecture 1: Attack on F2 & F7 (Weak Focal Points f2 f7)",
      "Lecture 2: Caro kann exchange Carsbad pawn structure- Minority Attack Plans",
      "Lecture 3: Candidate Moves Part 2",
      "Lecture 4: Exchange Sacrifices",
      "Lecture 5: Color Complex Weekness",
      "Lecture 6: Trigran Petrosian- Caro Kann",
      "Lecture 7: Student games analysis",
      "Lecture 8: Tactics- Tal",
      "Lecture 9: The Bishop Pair",
      "Lecture 10: Caro Kann Advance Variation",
      "Lecture 11: Art of Sacrifice",
      "Lecture 12: Test-1",
      "Lecture 13: Arjun Erigaisi",
      "Lecture 14: Grob Openning",
      "Lecture 15: Improving the worst Pieces",
      "Lecture 16: Student Game Analysis",
      "Lecture 17: Pawn Structure- IQP",
      "Lecture 18: Defensive Moves- part 2",
      "Lecture 19: Rook endgame( Pawn on 7th Rank)",
      "Lecture 20: Student Game Analysis",
      "Lecture 21: Vishy Anand- the Lighting KID of India",
      "Lecture 22: London System Full Revison",
      "Lecture 23: Focal Point Attack",
      "Lecture 24: Test 2",
      "Lecture 25: Scotch Opening",
      "Lecture 26: Mate in 4 Practice",
      "Lecture 27: c4 & c5 Ideas in Hanging Pawn Structure",
      "Lecture 28: Revision Carlsbad structure and IQP",
      "Lecture 29: Fortress",
      "Lecture 30: Zugzwang",
      "Lecture 31: Theoretical Queen Endings",
      "Lecture 32: student game analysis",
      "Lecture 33: Tactical Trainning- Interferance",
      "Lecture 34: Tactical Trainning- Colliner Moves",
      "Lecture 35: Student games analysis",
      "Lecture 36: Test-3",
    ],
  },
  {
    level: "INTERMEDIATE_2",
    label: "Intermediate Level 2",
    codePrefix: "IM2",
    lectures: 36,
    durationMonths: 4,
    topics: [
      "Lecture 1: Revision- Pawn structure- IQP",
      "Lecture 2: Revision- Pawn structure- Hanging Pawn Structure + Minority Attack",
      "Lecture 3: Flank Attack",
      "Lecture 4: Positional Queen Sacrifice",
      "Lecture 5: Opening Ruy Lopez (Chigorin, Breyer setup)",
      "Lecture 6: Karpov- Caro Kann",
      "Lecture 7: Student games analysis",
      "Lecture 8: Tactics- Carlsen",
      "Lecture 9: Rook Endgame- Theoretical 6th rank pawn",
      "Lecture 10: pawn structure Maróczy Bind → Introduction & Main Ideas",
      "Lecture 11: Opening- Queen’s Gambit Traps",
      "Lecture 12: Test-1",
      "Lecture 13: Opening- Benoni Advance Pawn",
      "Lecture 14: Opening- Benko Gambit – Volga Pawn Structure",
      "Lecture 15: Opening Traps",
      "Lecture 16: Theoretical Knight Endgame",
      "Lecture 17: Checkmate with Knight + Bishop",
      "Lecture 18: Tactical Trainning- Knight vs Knight Endgame( medium Level)",
      "Lecture 19: Strategical Training- Converting Bishop Endings(Medium Level)",
      "Lecture 20: Student Game Analysis",
      "Lecture 21: Capablanka vs Marshall",
      "Lecture 22: Pual Morphy – The Legend (Endgame ideas)",
      "Lecture 23: Focal Point Attack (h6 -h3) weekness",
      "Lecture 24: Student Game Analysis",
      "Lecture 25: Opening- Sicillian Dragon",
      "Lecture 26: Tactical Trainning- King Side Attack",
      "Lecture 27: Sacrifice the piece for 2 pawns",
      "Lecture 28: Openning – Scotch Gambit Detailed",
      "Lecture 29: Mate in 4 Practice",
      "Lecture 30: Sicillian Delayed Alpin",
      "Lecture 31: Carokann side variations",
      "Lecture 32: Tactical Trainning- Queen Side Attack( Level Medium)",
      "Lecture 33: Tactical Trainning- Zugzwang",
      "Lecture 34: Theoretical Queen Endings (queen vs Rook) - part 2",
      "Lecture 35: student game analysis",
      "Lecture 36: Test-3",
    ],
  },
  {
    level: "INTERMEDIATE_3",
    label: "Intermediate Level 3",
    codePrefix: "IM3",
    lectures: 40,
    durationMonths: 4,
    topics: [
      "Lecture 1: Dynamic Pawn structure- Maroczy, Benoni, Benko",
      "Lecture 2: Statatic Pawn structure- Hanging Pawn Structure,Carlsbud, IQP",
      "Lecture 3: Tactics- Mate in 5 Practice",
      "Lecture 4: Opening- Sicilian Nimzowitch",
      "Lecture 5: Opening- French Defence",
      "Lecture 6: Ulf Anderson- Poet Of Endgames",
      "Lecture 7: Student games analysis",
      "Lecture 8: The Robert James Fischer- One and only Bobby Fischer",
      "Lecture 9: Rook Endgame- One Extra Pawn Convertion",
      "Lecture 10: pawn structure Schevengien - Ideas",
      "Lecture 11: Opening- Queen’s Gambit Declined",
      "Lecture 12: Test-1",
      "Lecture 13: Model Games- Sicillian Nimzowitch",
      "Lecture 14: Prophylactic Thinking- part 1",
      "Lecture 15: Endgame- Rook vs Knight",
      "Lecture 16: Endgame Tactics- Knight Endings- part 2",
      "Lecture 17: Slow Buildup Atack",
      "Lecture 18: Tactical Trainning- Rook Endings – Part 2",
      "Lecture 19: Tactical Training- Pawn Endings(part 2)",
      "Lecture 20: Student Game Analysis",
      "Lecture 21: Opposite Colored Endings",
      "Lecture 22: Botwnik – The Legend ( Mikhail Botvinnik vs. Vasily Smyslov )",
      "Lecture 23: Focal Point Attack (h6 -h3) weekness- part 2",
      "Lecture 24: Student Game Analysis",
      "Lecture 25: Opening- Closed Catalan",
      "Lecture 26: Opening – Open Catalan",
      "Lecture 27: Test 2",
      "Lecture 28: Opening – Neo Ctalan",
      "Lecture 29: Weak Squares",
      "Lecture 30: Focal Point Attack",
      "Lecture 31: Stop Opponent from Castling(attack on central king)",
      "Lecture 32: Queenless Middlegame",
      "Lecture 33: Tactical Trainning- Zugzwang(hard)- part 2",
      "Lecture 34: Bahr’s Rule in Pawn Structure",
      "Lecture 35: student game analysis",
      "Lecture 36: Long Tactics- Siezing the Advantage",
      "Lecture 37: Triotsky System",
      "Lecture 38: Student games analysis",
      "Lecture 39: Attack on Castled King",
      "Lecture 40: Test-3",
    ],
  },
  {
    level: "ADVANCE_1",
    label: "Advance Level 1",
    codePrefix: "ADV1",
    lectures: 48,
    durationMonths: 6,
    topics: [
      "Lecture 1: Revision- Volga Benko Struture",
      "Lecture 2: Statatic Pawn structure- Hanging Pawn Structure, IQP",
      "Lecture 3: Dynamic Pawn Strcutures",
      "Lecture 4: Rook end with extra a-h passed pawn",
      "Lecture 5: Opening- English( Reverse Sicillian Ideas from White)",
      "Lecture 6: Yuri Abarbakh- Endgame Genius",
      "Lecture 7: Student games analysis",
      "Lecture 8: Opening Sicillian Delayed Alpin- Basman Pantnik Gambit",
      "Lecture 9: Opening Semi Slav",
      "Lecture 10: pawn structure Rosolimo Attack",
      "Lecture 11: Opening- French Winawer",
      "Lecture 12: Test-1",
      "Lecture 13: Opening- Sicillian Nimzowitch",
      "Lecture 14: Prophylaxix- part 2",
      "Lecture 15: Endgame- Rook deep ideas",
      "Lecture 16: 7th Rank Theoretical Plans in Rook Endgame",
      "Lecture 17: Opening- Grunfeld – Dynamic center Attack",
      "Lecture 18: Pawn Endings(Mixed theory Practice)",
      "Lecture 19: Endgame long calculation- part 1",
      "Lecture 20: Student Game Analysis",
      "Lecture 21: Opposite Colored Bishops Endings",
      "Lecture 22: Restriction and paralysis",
      "Lecture 23: Focal Point Attack (h6 -h3) weekness- part 3",
      "Lecture 24: Student Game Analysis",
      "Lecture 25: Opening- Nimzo Indian",
      "Lecture 26: Model Games- Nimzo Larsen",
      "Lecture 27: King Side Attack- Hard Tactical Trainning", // Renumbered due to skip in source
      "Lecture 28: Weak Squares and strong square",
      "Lecture 29: AGM Naman Kaushik- Practical Tournament Games Analysis",
      "Lecture 30: Revision- Full Knight Endings (Theoretical)",
      "Lecture 31: Revision- Full Bishops Endings (Theoretical)",
      "Lecture 32: Tactical Trainning- Zugzwang(hard)- part 3",
      "Lecture 33: Revision- Full Rook Endgame (Theoretical)",
      "Lecture 34: Test 3",
      "Lecture 35: Tactical Trainning Defensive Moves- Hardest – part 4",
      "Lecture 36: Student games analysis",
      "Lecture 37: Long Tactics- Convert By Simplification",
      "Lecture 38: Stonewall attack",
      "Lecture 39: Opening- Caro kann Advance in detail",
      "Lecture 40: Opposite Side Flank Attack",
      "Lecture 41: Opening – Caro Kann Classical variation- side prep for tournaments",
      "Lecture 42: Initiative",
      "Lecture 43: Endgame By Flear G.",
      "Lecture 44: Art of Manovering- Midgame",
      "Lecture 45: Student Game Analysis",
      "Lecture 46: Final Test 4",
    ],
  },
];

export const SYLLABUS_MAP = SYLLABUS.reduce((acc, syllabus) => {
  acc[syllabus.level] = syllabus;
  return acc;
}, {} as Record<BatchLevel, SyllabusLevel>);
